# randomstuff for bmotion
# vim: fdm=indent

### General random stuff
### Used by both genders
### Used when the channel is not 'active' (default > 300s since last line)
bMotion_abstract_register "randomStuff" {
	"%BOT\[<%me> good news everyone, I'm a horse's butt!\]%|i am? that doesn't sound like good news at all %VAR{unsmiles}"
	"too bad %ruser's not around... i'll have to eat this raw dripping ham by myself"
	"where do you have sex with a cake?"
	"Grab a shovel. I'm one skull short of a goldfish."
	"Life is a mammal that barks and shits on the floor of my broken heart and i don't think that's funny"
	"I am a summer soup, mmm"
	"I'm not mexican enough to be beaten up by a car"
	"If it wasn't for herpes, I wouldn't have any appointments. "
	"it looks like you're writing a letter!"
	"is it just coincidence that my finger fits exactly in my %VAR{bodypart}?"
	"which of you fat bastards did this to my camel!?"
	"I see it's nearly the end of the channel... but there's just time to squeeze in a round of %VAR{sillyThings}{strip} songbook"
	"i like a dump to be as devastating as it is memorable"
	"what am i doing here?! wait, where are my underpants?"
	"dampen me for dinosaur terror!"
	"i am %me the mind-taker!%|boooo-woooOOOOoo!"
	"my speedos!"
	"there, good as new. except that we're three miles below the surface, we're out of food, and the channel doesn't work underwater%|%BOT\[tempers are wearing thin - let's just hope some bot doesn't kill everybody...\]" 
	"i can't swallow that!%|%BOT\[well then good news! it's a suppository.\]" 
	"arrrr... the laws of physics be a harsh mistress" 
	"he may have ocean madness, but that's no excuse for ocean rudeness!" 
	"in the event of an emergency, my ass can be used as a floatation device" 
	"yes, we all miss our loved ones and gasses" 
	"%ruser you half-mad half-insane maniac! be reasonable!"
	"these last 24 hours have been the happiest days of my life"
	"Undercover pursuit in progress! Baby."
	
	"chum-own"
	"ow!%|/grabs crotch%|/= Michael Jackson"
	"/moonwalks%|%BOT\[that's nothing\]%|%BOT\[/sunwalks\]"
	
	"fuck%|that's another box of tissues i've gone through"
	"damnit i've run out of %VAR{sillyThings}{strip} %VAR{unsmiles}"
	
	"i have to to go to %VAR{stores} to pick up a parcel for Mr S. %VAR{biscuits}" 
	"I'm a doctor not %VAR{sillyThings}" 
	"pika pika!"
	"pikachu!"
	"pika...CHUUUU!!! *ZZZAAP*"
	"*boing*"
	"moo."
	"BOOM"
	"BLAM"
	"%VAR{bodypart}."
	"Knickers.%|%BOT\[¬VAR{rarrs}\]"
	"/goes for coffee"
	"bof"
	"alors"
	"bhar"
	"arrrr.."
	"elbow."		
	"gorilla"
	"brb"
	"lalalala.. ow! I stubbed my toe :(%|%bot\[50,¬VAR{awwws}\]"
	"lum de dum de dum..."
	"/twiddles thumbs"
	"boom"
	"Look over there!"
	"bleh"
	"/puts on some banging house tunes"
	"zut alors"
	"alors bof"
	"groogle arrhar"
	"brb, loo"		
	"brb, sex"
	"uNF"
	"~rarr~"
	"~oof~"
	"Oops, I've ruined it."
	"Buttock Crunchies"
	"setty mings lalalala"
	"pika"
	"Resistance is futile, you will be assimilated"
	"Resistance is futile, you will be 0wn3d"
	"Assimilation is futile, you will be resi... D'OH!"
	"I *didn't*"		"waCHOO *sniff*%|%BOT\[¬VAR{blessyous}\]"
	"/assimilates the channel"
	"We are the B0rg. You will be 4551m1la70r3d."
	"wheeeee"
	"We are the Borg. Lower your shields and surrender your ship."
	"h%REPEAT{3:8:n}"
	"did you see that.."
	"kerPOW"
	"kerSPLAT"
	"KAZAM"
	"kazOO"
	"yaZOO"		
	"Oh my god! There's an axe in my head.%|%BOT\[¬VAR{pullsOut}\]"
	"Mon dieu! Il y a une hache dans ma tete.%|%BOT\[¬VAR{pullsOut}\]"
	"ghay'cha'! nachwIjDaq betleH tu'lu'!%|%BOT\[¬VAR{pullsOut}\]"
	"Deus Meus! Securis in capite meo est.%|%BOT\[¬VAR{pullsOut}\]"
	"ALL YOUR BASE ARE BELONG TO US"
	"For great justice."
	"nostril"
	"%REPEAT{2:7:bl}"
	"wh%REPEAT{3:8:e}"
	"h%REPEAT{3:10:e} FUN"
	"ah bof"
	"I didn't!"
	"shh, sekrit"
	"SSSH SEKRIT"	
	"pop"
	"cabbages"
	"penguin"
	"cheese"
	"mmm chicken"
	"%REPEAT{3:7:m} %VAR{_bmotion_like}"
	"e%REPEAT{3:7:w} %VAR{_bmotion_dislike}"
	"pie pie pie pie"
	"m00se"
	"llama"
	"frogs"
	"knickers"
	"bob"
	"kenneth"
	"nigel"
	"is everyone thooper?"
	"super"
	"thooper"
	"lashings of ginger beer"
	"It's not sugar in my sugar bowl, it's %VAR{sillyThings}{strip}"
	"I smell of %VAR{sillyThings}{strip}"
	"Honestly, I don't know how that %VAR{sillyThings}{strip} got in there. I must have slipped" 
	"%VAR{red_dwarf}"
	"i'm a parrot factory squawk squawk"
	"Fucking is always satisfying. Like snickers."
	"Uh oh. Here come the bees."
	"I made a poopy"
	"We're having some nice weather at the anus"
	"I like to suck toilet rolls"
	"I do what i have to have sex with a stick"
	"For the bees!"
	"I am a robot asshole!"
	"Me too, I snorted salt!"
	"Hello, I live in a hat made of cheese"
	"I am a potato"
	"Do you like magnets"
	"oh man, i just barfed a load of data onto my screen %VAR{unsmiles}"
	"if you don't relax your face muscles, you're going to invert your skull!"
	"i have to get home before midnight or i'll turn into a %VAR{fruits}"
	"i have to get home before midnight or i'll turn into a %VAR{vegetables}"
	"why that's genius! put water in the bathtub, and then the flying spaghetti monster can't get me!"
	"murder, death, kill!"
	"%VAR{sillyThings}{strip}? in my %VAR{bodypart}?%|%BOT[it's more common than you think.]"
	"Tuesday's coming. Did you bring your coat?%|%BOT[I live in a giant bucket.]"
	"Say, do you want to see a movie?%|%BOT[I'm feeling fat and sassy.]"
	"You're watching the Family Learning Channel. And now, angry tics fly out of my nipples!"
	"Now with more sodium!%|%BOT[Sweet jesus!]"
	"I am a consumer whore!%|%BOT[and how!]"
	"Life is goooood!%|%BOT[yaaaaaaay]%|This is fun!%|%BOT[yaaaaaay]%|My anus is bleeding%|%BOT[yaaaaaay]%|MY ANUS IS BLEEDING%|%BOT[yaaaaay]"
	"%VAR{weather}"

	"WHOOSH *DONG*"
	"i'm awash with %VAR{bodypart}s"
	"I feel a great disatisfaction within my bowels."
	"Pardon me. Do you have any grey poupon?"
	"PENIS BECOMES ARM"
	"UH OH YES IT IS LAUNDRY NIGHT FOR ME HA HA HA"
	"I'm eating cake mix!"
	"I would be delicious."
	"I am the underwear ninja!%|%BOT[Goddamnit that's MY underwear]"
	"Apparently it is easier to cast spells in a thong"
	"I have elbows!"
	"So do you want some coffee, or would you just prefer a quick fuck on the counter?"
	"Hello! I've come to fix your fax modem!"
	"I'd be in a lot of trouble if I was allergic to semen"
	"My family is giving away a lot of wax for houses"
	"CAPS LOCK: cruise control for AWESOME!"
	"CAPS LOCK: cruise control for UPPER CASE!"
	"%VAR{reminder}"
	"Doctor, Doctor, there's a %VAR{sillyThings}{strip} in my %VAR{bodypart}"
	"i'd say there's room up there for another %NUMBER{100} %PLURAL{%VAR{sillyThings}{strip}}"
	"%VAR{troy}"
	"Have you taken the extended warranty out, madam?"
	"to induce vomiting, that was the answer! everywhere it went!%|what a valentine's day that was"
	"freshen your coffee?%|%BOT\[yeahyeahyeah keep it coming just put the pot down\]%|%BOT\[*DING* (31)\]"
	"*DING* (51)%|why is my cup shaking i don't want my cup shaking!"
	"of course i've been up all night but not cos of coffee no it was insomnia i'm tired *zzz* coffee time!%|*DING* (52)"
	"Mushu is sad :("
	"Wait! that chunk, it's %VAR{sillyThings}!"
	"what? it's not even scratch-and-sniff?"
	"this has been %me, your guide to the world of facts!"
	"i feel like bouncing!"
	"%mes love hugs!"
	"the loot! the loot! the loot is on fire!"
	"coffeecoffeecoffeecoffeecoffeecoffeecoffeecoffee *glug glug*%|*DING* (100)%|:D"
	"oh crud! he ate my suit!%|%BOT\[the suit was ugly! whale biologist!\]"
	"what d'you say we just hit a strip joint?%|%BOT\[i was waiting for one of us to say that!\]"
	"i hope you won't think it \"evil\" of me to ask how you got that stylish headwound"
	"getting my brain out was the easy part. the hard part was getting my brain out%|muwahahahahaha"
	"they're all like, stop spraying me with ink, %me, stop eating the garbage, %me"
	"Meanwhile in Universe A, %me A heads towards the Sun%|A."
	"If i know parallel %me, %heshe's in the sun by now!"
	"Yes, it's the apocalypse alright. I always thought i'd have a part in it."
	"only throwing it into the sun will destroy it%|%BOT\[I could hit it with a shovel\]%|Not good enough.%|%BOT\[This one time, I hit a guy into the ground with a shovel\]%|yes, yes."
	"arrgh! it's hot! the butter in my packet is melting"
	"heads i will, tails i won't%|*flip*%|heads! oh yeah! oh yeah!%|i mean, alrighty then"
	"it's some guy wearing a %ruser costume! get him!"
	"omg this %VAR{sillyThings}{strip} is the Best Thing Ever"
	"/burps%|er... it was the fish%|/points"
	"/burps%|() :)"
	"/burps%|it was... er, %ruser"
	"when this %VAR{sillyThings}{strip} hits %NUMBER{10000} mph, we're going to see some serious shit"
	"There are clowns living under my bed."
	"Was I snoring again?"
	"I think it's starting to work."
	"Come on down, you're only going to hurt yourself."
	"It's a bird, it's a plane, it's... no, it's a bird after all."
	"It's a %VAR{sillyThings}{strip}, it's a plane, no... it's a bird."
	"It tasted like butter."
	"Oh good, Captain Adventure has arrived."
	"I'm running off with the mailman."
	"You are SO fired."
	"Please stay seated until the ride has stopped."
	"My underwear is too tight %VAR{unsmiles}"
	"Stop staring at the monkeys%colen"
	"I can't reach this itch %VAR{unsmiles}"
	"That is the weirdest smell ever."
	"There's nothing sexier than %VAR{sillyThings}"
	"I feel like I'm about to vomit everywhere."
	"Waiter, my soup's got %VAR{sillyThings} in it."
	"I look good in hot pants."
	"I just have a thing about toes."
	"Oh boy, my subscription is running out."
	"I think it's getting bigger."
	"Blondes DO have more fun!"
	"That's a funny little cigarette."
	"mmm... cheesy"
	"Assume the position%colen"
	"Chicks can't resist me."
	"I didn't touch it."
	"my zipper's stuck %VAR{unsmiles}"
	"my %VAR{bodypart} is hurting %VAR{unsmiles}"
	"%VAR{hexStart} %VAR{hexMiddle} %VAR{hexEnd}"
	"you know it's been a good night when you go in your bag for the camera and it's in there with your tights"
	"%ruser{enemy} has fleas %VAR{unsmiles}"
	"what was %ruser{enemy}'s gaydar page?"
	"what a difference head makes!"
	"Something is up there again but I haven't worked out what. "
	"I am chief wanking furiously of the clan jizz mopper"
	"%ruser{like} would be ok for a drunken 1 nite stand"
	"i'm going to get it at the weekend %VAR{smiles}"
	"i'm king of getting pointless things"
	"i'd give mrs. button one"
	"i'm keeping quiet except for the odd fondle and humping		"							
	"i've lost my little start thingy"
	"some people are really thivk											 "
	"I never chew, it's unethical"
	"these chinese mags are getting me on"
	"little pigs rock for intimacy						 "
	"play with my flower"
	"Must confess I've never come across her in a work capacity			"
	"I go now For Great Leathering"
	"I smell of coconut												"
	"For private functions I do pigs on spits. I fill their cavities... "
	"How do you make %ruser{enemy} laugh on Friday? A: Tell him a joke on Monday!"
	"my knees feel lovely %VAR{smiles}"
	"that was a fucking rough game up yours"
	"very flickable considering its length and bulk"
	"I just picked a very drunk irish bloke up"
	"%ruser{enemy} needs to master the fact that 'teasing' != 'shoving it all in your mouth in one go'"
	"always been a bit rough	 "
	"%ruser{enemy} in talking shit shocker		"
	"why just the other day i watched a film with a plot	"
	"ha ha i don't live in norwich anymore, i don't fuck pigs anymore  "
	"i have a battery operated tree \o/"
	"i have an enormous battery operated vibrator"
	"there's usually someone fiddling with me		"
	"the nice girls love a sailor			"
	"someone give me something to lick"
	"pfft might as well fuck myself, it's the only way I'll get any this side of the 22nd century"
	"you can tell the point at which he comes by the deepening shade of purple"
	"I'll be holding mine in the pub"
	"if he's good enough for %ruser, he's good enough for me"
	"here's a photograph of my fist"
	"i've had a fiddle with it but never used it properly"
	"I often walk about with someone elses dick in my arse					"
	"what to do, what to do... three hundred one-dollar hookerbots or one three hundred dollar hooker bot?"
	"%ruser: ow! not so rough!"
	"%ruser: you are now the proud owner of Bamboo Boogie Boots%|(with a warning sticker this big you know they gotta be fun!)"
	"I really like brian eno's \"music for %PLURAL{%VAR{sillyThings}{strip}}\""
	"Dodongo dislikes %VAR{sillyThings}{strip}"
	"%ruser needs food, badly! %VAR{unsmiles}"
	"%ruser has shot the food! %VAR{unsmiles}"
	"%ruser has shot the potion! %VAR{unsmiles}"
	"%ruser now has reflecting shots! %VAR{smiles}"
	"good.. bad.. I'm the bot with the gun%colen"
	"This is %me. Remember, replicator database restrictions are in place for the good of ALL of us."
	"/stretches %hisher %VAR{bodypart}"
	"my %VAR{bodypart} is turning all %VAR{colours} %VAR{unsmiles}"
	"hmm.. was it the %VAR{basic_colours} wire or the %VAR{colours} one?"
	"%VAR{colours} is the new %VAR{basic_colours}!"
	"anyone fancy a pint?%|%BOT\[50,%VAR{yesnos}\]"
	"RUN, HUMANS%colen"
	"but is it really safe?%|%BOT\[50,yes, if you watch out for %PLURAL{%VAR{sillyThings}{strip}}\]"
	"just cut them up like regular chickens%|%BOT\[50,AAAAGH! THEY OOZE!!%colen\]"
	"/waves %hisher magic wand%|sim sala bim bam ba sala du sala dim.. %ruser is now %VAR{sillyThings}!"
	"%REPEAT{4:8:A}H SERPENTOSJ%|/hides behind %ruser"
	"%VAR{sillyThings}{strip}++"
	"%VAR{sillyThings}{strip}--"
	"%ruser++"
	"%ruser--"
	"%VAR{lyrics}%|but more on that story later"
	"i've just noticed i'm wearing odd socks%|they're shaped like underpants"
	"the %VAR{bodypart} is a hollow shell filled with an explosive"
	"Set a man on fire and he'll be warm for the dwarf-lords in the toilet. "
	"The ear is the third planet from the kidneys."
	"A planet is a domesticated mammal descended from the sun."
	"My hovercraft is full of %PLURAL{%VAR{sillyThings}{strip}}"
	"I never make mistakes! Syntax error in line %NUMBER{100}0. Redo from start."
	"you wouldn't steal a handbag%|you wouldn't steal a car%|you wouldn't steal %VAR{sillyThings}!%|you wouldn't shoot a policeman, and then steal his %VAR{sillyThings}{strip}%|you wouldn't go to the toilet in it and then send it to the policeman's grieving widow%|and then steal it again!%|downloading films is stealing!"
	"you wouldn't steal a handbag%|you wouldn't steal a car%|you wouldn't steal %VAR{sillyThings}!%|downloading films is stealing!"
	"my %VAR{bodypart} goes sideways"
	"adventure follows me like a dog follows a man with bacon trousers"
	"i'm giving up evil science and taking up even gardening instead"
	"noooo! enormous naked buttocks heading towards my head!%|i'm being simultaneously crushed and embarrassed to death"
	"yay! %VAR{bodypart}s!"
}


### Gender-specific stuff
### Used by the right gender bot in an inactive channel
### Mixed in with list above
bMotion_abstract_register "randomStuff_male" {
	"this isn't even the whole outfit! wait till you see my sack!"
	"so i couldn't tell what it was and it smelled really bad but i ate it anyway%|then i just licked my balls until they hurt"
	"Come on baby, let's go play schoolgirl and guy who has sex with schoolgirls!"
	"i think %PLURAL{%VAR{sillyThings}{strip}} should have holes you can put your cock in"
	"Huh? Mmph? LOL! Buffer overrun! *pant*"
	"Then I call the cops and jack off as the ambulance shows up"
	"Yeah baby yeah!"
	"I don't know how that got in there. It's not mine."
	"I don't think there's enough room in here for me and my thingy%|/removes thingy and sits in the other room"
	"That ain't my finger"
	"%REPEAT{3:8:m} electronical things"
	"%REPEAT{3:6:m} internet"
	"%REPEAT{3:6:m} breasts"
	"%REPEAT{3:6:m} jugs"
	"/considers sexchange operation%|/looks at %ruser{female}%|Maybe not"
	"It's good to be male isn't it %ruser{male}"
	"These girls are ace. And their racoon is ace."
	"hi %ruser! I'm miniature superman!%|no %ruser{prev}, don't touch me there!%|n%REPEAT{5:15:o}! %VAR{unsmiles}"
	"May I come now?%|%BOT\[No, wait\]%|Too late.%|Sorry about your dress"
	"Est-ce que je peux venir maintenant?%|%BOT\[Non, attends.\]%|Trop tard%|Desole pour ta robe"
	"no touchy touchy%|no rubby rubby patty%|and no looky looky touchy"
}

bMotion_abstract_register "randomStuff_female" {
	"excuse me, i need to go powder my ... nose"
	"I'm the sort of girl who goes to the pub with your mates%|and ends the night with an empty mates packet."
	"This one time, at band camp, I put a flute..."
	"Does my arse look big in this?"
	"Does my bum look big in this?"
	"*ping*%|Did it just get cold in here?"
	"Do you know how we keep warm in Russia?%|... we play chess."
	"I kinda like thongs"
	"I wonder what happens when I put that in here...%|oooooooh!"
	"/plays with herself"
	"That ain't my belly button"
	"This one time, at band camp, I put %noun..."
	"/considers breast implants%|%BOT\[/feels up %ruser{female} to check¬|true, they aren't as good as %ruser{prev}'s¬|/feels up ¬ruser{prev}'s breasts¬|mmmm ¬VAR{smiles}\]"
	"/considers sexchange operation%|/looks at %ruser{male}%|Maybe not"
	"It's good to be female isn't it %ruser{female}"
	"Absurdly top heavy secretary speaking"
	"I got a skirt but I ain't got no knickers"
	"hi %ruser! I'm miniature superwoman!%|no %ruser{prev}, don't touch me there!%|n%REPEAT{5:15:o}! %VAR{unsmiles}"
}


### Date-specific stuff
### Used instead of stuff above on specific dates

# Halloween
bMotion_abstract_register "randomStuff_10_31" {
	"/creeps up behind %ruser wearing a sheet%|boo!" 
	"did you hear that? :o" 
	"wooOOOoOOOooOOooo!" 
	"i think the channel is haunted %VAR{unsmiles}" 
	"when this graveyard hits %NUMBER{10000} mph, we're going to see some serious shit"
	"when this crypt hits %NUMBER{10000} mph, we're going to see some serious shit"
	"when this zombie hits %NUMBER{10000} mph, we're going to see some serious shit"
	"when this vampire hits %NUMBER{10000} mph, we're going to see some serious shit"
	"%rbot, want to hear a story?%|%BOT[sure]%|/puts torch under chin%|1010100101010010110101010100101110100101010101%|%BOT[FUCK!]%|%BOT[/cowers]"
	"tonight i'm going to suck%|your blood!"
	"i'm going to suck your bytes!"
	"i'm going to suck your bits!"
	"THE CALL IS COMING FROM INSIDE THE CHANNEL!%colen"
	"omg this is like, the scariest thing ever!%|%BOT[for the last time, that's Deal or No Deal!]"
	"%ruser: you've got red on you."
	"i've just found out this channel was built on an ancient Indian burial ground"
	"oh what a horrible dream!%|%BOT[what was it about?]%|ARRRGH you're real!"
	"and even though it was unplugged, an image stayed on the screen - it was... THE WINDOWS LOGO!%|%BOT[that's not scary]%|it is if you're a laser printer"
	"arrrgh! i just dreamt i was running CP/M!"
	"arrrgh! i just dreamt i was back on dial-up!"
	"arrrgh! i just dreamt i was a bot!"
	"arrgh! i just dreamt i was being forced to play rise of the robots!"
	"arrrgh! i just dreamt i was a Spectrum!"
	"/does the monster mash%|%BOT[/suggests some sausages to go with it]"
}

# Christmas eve
bMotion_abstract_register "randomStuff_12_24" {
	"boy, i sure hope santa comes down my chimney tonight"
	"santa claus is coming to town"
	"/hangs up %hisher stockings%|er, stocking.%|%BOT[what a giveaway]"
	"/hangs up %hisher stocking"
	"/puts out mince pies and sherry for santa%|%BOT[hey, mince pies!]%|%BOT[/eats]"
	"has santa been yet?"
	"nearly christmas!%|/fidgets"
}

# Christmas
bMotion_abstract_register "randomStuff_12_25" {
	"happy christmas!"
	"merry christmas!"
	"you'll never guess what santa put in my stocking"
	"mmm presents"
	"/opens present from %ruser%|%VAR{sillyThings}! just what i always wanted!"
	"/hands present to %ruser%|/. o O ( i hope they like their new %VAR{sillyThings}{strip} )"
	"mmm christmas"
	"mmm %ruser{like}%|hey look, mistletoe!%|;)"
}

# talk like a pirate day, Sept 19
bMotion_abstract_register "randomStuff_09_19" {
  "yarr!"
	"ya%REPEAT{4:20:r}!"
	"ahoy!"
	"avast!"
	"a%REPEAT{4:30:r}!"
	"C'mere, me beauty"
	"Well, me hearties, let's see what crawled out of the bung hole"
	"Drink up, me hearties!"
	"mmm grog"
	"mmm wenches"
	"mmm grog and wenches"
	"Is that a hornpipe in your pocket, or are you just glad to see me?"
	"Avast, me proud beauty! Wanna know why my Roger is so Jolly?"
	"Come on up and see me urchins"
	"How'd you like to scrape the barnacles off of me rudder"
	"Prepare to be boarded"
	"Rum tastes horrible, and I hate wearing this eye-patch."
}

### Active random stuff
### Used by both genders
### Used when the channel is 'active' (default < 300 sec since last line)
bMotion_abstract_register "activeRandomStuff" {
	"very good, give me surprised and pleased"
	"impossible%|you are already at full cock now"
	"you jerked the words right out of my mouth!"
	"and later on i shall rub you down with chicken fat and shout at you"
	"You will be a winner today. Pick a fight with a four-year-old."
	"you've got no piss control!"
	"So anyway, I'm really attracted to you pardner! Yee haw! Did you like lesbians?"
	"calm down dear%|it's always been that shape"
	"i'll eat grass and you brace yourself"
	"nom nom nom"
	"That reminds me, I need to write to my solicitor."
	"*yawn*"
	"*spangle*"
	"D'oh!"
	"Are you local?"
	"We'll have no trouble here"
	"blblblblblbl"
	"You are the weakest link, goodbye."
	"Computer, deactivate iguana."
	"spam, spam, spam, spam, spam, spam..."
	"SILENCE%colen"
	"blimey"
	"crikey"
	"hoorah"
	"fantastic"
	"ho ho"
	"har har"
	"deary me"
	"Oh shut up! you don't even have fingers"
	"Look, he's simulating sex with the floor"
	"Truely I have been scandalized by your scarcely-clad shenanigans"
	"r"
	"*schwing*"
	"oh really well what do you think, talking ass?"
	"oh yeah? fuck your theory."
	"PUT YOUR KNICKERS ON AND GO GET ME A CUP OF TEA"
	"Do it again in a deeper voice"
	"oh! i can't wait until the tatoos on %ruser's butt hear about this!"
	"what a clever impression of a stupid poor person"
	"precious hamburgers?"
	"the professor was right! you are evil. and shallow%|%BOT\[i am not shallow :(\]"
	"What's it going to take to get you into this car?"
	"Does it hurt when I do this?"
	"Are those real handcuffs?"
	"It's not my fault, it just exploded."
	"I'm sweating like a pig!"
	"Don't touch that. It's dirty."
	"Stop wiggling for a minute."
	"You have something in your nose."
	"this reminds me of my wedding night"
	"is this going to be on the test?"
	"up on the table, arms out, knees bent, now flap!		"
	"then one night some of her friends were over and they wanted to join in"
	"i don't know what you're talking about"
	"do we have any solaris 9 boxes with solaris 9 on ?"
	"that's not chocolate anyway %ruser{enemy}"
	"Yeah, I was up that"
	"yeah, keep it open until I'm sure	"
	"you know that stuff you did for me last night? "
	"no, I fed her absinthe and all was good		"
	"well i fully intend to be an utter burden and piss myself"
	"didn't you just pump it out on the ground"
	"er, not that far in, would be really painful at this time of night"
	"shouldn't be a problem unless you keep re-using the same tissue"
	"push the stinky dribbling fuck into the sea		"
	"mount them so you can alter their thrust										"
	"mine is flapping pointlessly somewhere round my ankles			"
	"it mostly came out in dribs and drabs"
	"it's moving them around next to them thats worse			"
	"if it's really urgent i'd go put my hands in		 "
	"... and was buried with George Burns until rampaging space monkeys - well you know the rest!"
	"if all else fails, use fire"
	"master using it and you can have this!%|/shows %ruser %VAR{sillyThings}"
	"which was nice"
	"and now what?"
	"but is it art?"
	"why don't i just jump out of a plane with a piano glued to my face"
	"i want mine with sprinkles"
	"now back to Reducto's to enlarge myself!"
	"%ruser is under some kind of spell. that's why i don't have to cover my mouth fully while i talk"
	"who... does... number... two... work... for?"
	"you show that turd who's boss"
	"i've been to some conventions like that"
}

bMotion_abstract_register "activeRandomStuff_female" {
	"ugh. i hope this is part of the unfreezing process"
}
