
bMotion_abstract_register "adjective" {
"angry"
"awful"
"beaten"
"bloated"
"bloody"
"boney"
"broken"
"butchered"
"dead"
"decapitated"
"decaying"
"depraved"
"disgusting"
"dying"
"electric"
"eternal"
"evil"
"explosive"
"fat"
"frightening"
"frostbitten"
"frozen"
"furious"
"ghastly"
"gigantic"
"gnarled"
"greasy"
"grotesque"
"gutted"
"hated"
"hateful"
"hellish"
"horrible"
"huge"
"immortal"
"impaled"
"invisible"
"loathsome"
"lustful"
"macabre"
"magical"
"malnourished"
"massive"
"miniscule"
"miserable"
"morbid"
"murdered"
"naked"
"never ending"
"pathetic"
"perverted"
"raped"
"rotten"
"rusty"
"savage"
"screaming"
"shattered"
"skinny"
"slimy"
"small"
"suicidal"
"starving"
"terrible"
"terrifying"
"tiny"
"twisted"
"wicked"
"violated"
"volcanic"
"battle hardened"
"armored"
"titanic"
"powerful"
"burning"
"demonic"
"satanic"
"fascist"
"skeletal"
"withered"
"frenzied"
}

bMotion_abstract_register "adverb" {
"accidentally"
"angrily"
"badly"
"boldly"
"bravely"
"brutally"
"calmly"
"carelessly"
"courageously"
"cruelly"
"defiantly"
"elegantly"
"fatally"
"foolishly"
"gently"
"horribly"
"hungrily"
"joyously"
"madly"
"painfully"
"repeatedly"
"savagely"
"silently"
"speedily"
"stealthily"
"violently"
"vivaciously"
"wildly"
"tenderly"
}

bMotion_abstract_register "amount" {
"hundred"
"thousand"
"million"
"billion"
"hundred thousand"
"hundred million"
"hundred billion"
"massive army of"
"%NUMBER{100}"
}

bMotion_abstract_register "being" {
"angel"
"baby"
"barbarian"
"berserker"
"butcher"
"cannibal"
"child"
"child molestor"
"clown"
"cripple"
"demigod"
"demon"
"devil"
"dentist"
"dragon"
"fetus"
"god"
"goddess"
"golem"
"ghost"
"ghoul"
"giant"
"hermaphrodite"
"horse"
"incubus"
"king"
"knight"
"leech"
"leper"
"maggot"
"magician"
"masochist"
"man"
"maniac"
"monster"
"murderer"
"orphan"
"pagan"
"pedophile"
"priest"
"prince"
"princess"
"prostitute"
"psychopath"
"queen"
"rapist"
"retard"
"savage"
"skeleton"
"slave"
"sorcerer"
"spectre"
"succubus"
"superhuman"
"surgeon"
"undertaker"
"titan"
"troll"
"tyrant"
"vampire"
"virgin"
"warlock"
"warrior"
"werewolf"
"woman"
"wraith"
"whore"
"widow"
"witch"
"wizard"
"wolf"
"zombie"
"spider"
"nazi"
"metal guitarist"
"metal singer"
"hang man"
"boar"
"goat"
"peasant"
}

bMotion_abstract_register "beings" {
" angels"
"babies"
"barbarians"
"berserkers"
"butchers"
"cannibals"
"children"
"child molestors"
"clowns"
"cripples"
"demigods"
"demons"
"devils"
"dentists"
"dragons"
"fetuses"
"gods"
"goddesses"
"golems"
"ghosts"
"ghouls"
"giants"
"hermaphrodites"
"horses"
"incubi"
"kings"
"knights"
"leeches"
"lepers"
"maggots"
"magicians"
"masochists"
"men"
"maniacs"
"monsters"
"murderers"
"orphans"
"pagans"
"pedophiles"
"priests"
"princes"
"princesses"
"prostitutes"
"psychopaths"
"queens"
"rapists"
"retards"
"savages"
"skeletons"
"slaves"
"sorcerers"
"spectres"
"succubi"
"superhumans"
"surgeons"
"undertakers"
"titans"
"trolls"
"tyrants"
"vampires"
"virgins"
"warlocks"
"warriors"
"werewolves"
"women"
"wraiths"
"whores"
"widows"
"witches"
"wizards"
"wolves"
"zombies"
"spiders"
"nazis"
"metal guitarists"
"metal singers"
"hang men"
"boars"
"goats"
"peasants"
}

bMotion_abstract_register "metal" {
"brass"
"bronze"
"copper"
"gold"
"iron"
"lead"
"platinum"
"silver"
"steel"
}

bMotion_abstract_register "paintstuff" {
	"decaffeinated coffee"
"acid"
"bile"
"blood"
"bone marrow"
"dirt"
"dust"
"entrails"
"feces"
"guts"
"ice"
"lava"
"molten %VAR{metal}"
"mucous"
"mud"
"poison"
"radioactive waste"
"sand"
"semen"
"smegma"
"toxic waste"
"urine"
"venom"
"vomit"
"fungus"
"pus"
"magma"
"wine"
"ale"
"medical waste"
}

bMotion_abstract_register "paintbodypart" {
"anal cavity"
"anus"
"arm"
"bone"
"brain"
"colon"
"corpse"
"ear"
"eye"
"fecal matter"
"finger"
"foreskin"
"genital"
"gut"
"hand"
"heart"
"intestine"
"jawbone"
"liver"
"lung"
"nose"
"penis"
"ribcage"
"scalp"
"shoulder blade"
"skeleton"
"skin"
"skull"
"spine"
"stomach"
"tooth"
}

bMotion_abstract_register "paintbodyparts" {
"anal cavities"
"anuses"
"arms"
"bones"
"brains"
"colons"
"corpses"
"ears"
"eyes"
"feces"
"fingers"
"foreskins"
"genitals"
"guts"
"hands"
"hearts"
"intestines"
"jawbones"
"livers"
"lungs"
"noses"
"penises"
"ribcages"
"scalps"
"shoulder blades"
"skeletons"
"skins"
"skulls"
"spines"
"stomachs"
"teeth"
"vaginas"
}

bMotion_abstract_register "material" {
"brimstone"
"concrete"
"glass"
"metal"
"obsidian"
"stone"
"wood"
"%VAR{metal}"
"%VAR{paintbodyparts}"
}

bMotion_abstract_register "beingverb" {
"pouring %VAR{paintstuff} over"
"drinking %VAR{material} goblets of %VAR{paintstuff} with"
"attacking"
"burning"
"burying"
"celebrating victory over"
"dining with"
"dismembering"
"dissecting"
"dreaming of"
"drinking the blood of"
"eating"
"fellating"
"freezing"
"immolating"
"infecting"
"holding a funeral for"
"killing"
"molesting"
"mourning over the loss of"
"murdering"
"raping"
"rending the flesh of"
"sacrificing"
"screaming at"
"torturing"
"frightening"
"mummifying"
"ripping apart"
"dancing with"
"circumcising"
}

bMotion_abstract_register "place" {
"abyss"
"afterlife"
"arena"
"battleground"
"canyon"
"castle"
"cathedral"
"cave"
"cemetary"
"chamber"
"church"
"city"
"crater"
"desert"
"dungeon"
"forest"
"fortress"
"galaxy"
"graveyard"
"hell"
"inferno"
"jungle"
"labyrinth"
"mass grave"
"monastery"
"mountain"
"ocean"
"pit"
"prison"
"purgatory"
"river"
"sea"
"torture chamber"
"tower"
"universe"
"valley"
"volcano"
"wasteland"
"world"
"planet"
"mach truck"
"freight train"
"prison cell"
}

bMotion_abstract_register "thing" {
"axe"
"boulder"
"cauldron"
"chain"
"coffin"
"fetus"
"flail"
"hammer"
"heart"
"knife"
"nail"
"planet"
"sawblade"
"skull"
"spear"
"spike"
"star"
"stone"
"sun"
"sword"
"syringe"
"tombstone"
"thorn"
"wand"
"warhammer"
"whip"
"electric guitar"
"drum kit"
"drumming machine"
"battle axe"
"bible"
"chainsaw"
}

bMotion_abstract_register "things" {
"axes"
"boulders"
"cauldrons"
"chains"
"coffins"
"fetuses"
"flails"
"hammers"
"hearts"
"knives"
"nails"
"planets"
"sawblades"
"skulls"
"spears"
"spikes"
"stars"
"stones"
"suns"
"swords"
"syringes"
"tombstones"
"thorns"
"wands"
"warhammers"
"whips"
"electric guitars"
"drum kits"
"drumming machines"
"battle axes"
"bibles"
"chainsaws"
}

bMotion_abstract_register "thingverb" {
"raining %VAR{paintstuff} over"
"crashing into"
"crashing through"
"crushing"
"destroying"
"exploding over"
"flying over"
"landing on"
"obliterating"
"transforming into"
}

bMotion_abstract_register "selfverb" {
"raining %VAR{paintstuff} over each other"
"drinking %VAR{material} goblets of %VAR{paintstuff} with each other"
"pouring %VAR{paintstuff} over each other"
"attacking each other"
"burning each other"
"burying each other"
"going to war with each other"
"dining with each other"
"dismembering each other"
"dissecting each other"
"dreaming of each other"
"drinking the blood of each other"
"eating each other"
"fellating each other"
"freezing each other"
"immolating each other"
"infecting each other"
"holding a funeral for each other"
"killing each other"
"molesting each other"
"preparing for battle"
"murdering each other"
"raping each other"
"rending the flesh of each other"
"sacrificing each other"
"screaming at each other"
"torturing each other"
"frightening each other"
"mummifying each other"
"ripping each other apart"
"dancing with each other"
"circumcising each other"
"having an orgy"
"head banging"
"committing suicide"
"dancing"
"sleeping"
"dying"
"rocking out"
"crashing into each other"
"crashing through each other"
"crushing each other"
"destroying each other"
"exploding over each other"
"flying over each other"
"landing on each other"
"obliterating each other"
"jamming"
}


bMotion_abstract_register "nice_adjective" {
	"happy"
	"nice"
	"intact"
	"clean"
	"curvy"
	"alive"
	"lovely"
	"sexy"
	"pretty"
	"cute"
	"reassuring"
	"normal-sized"
	"loving"
	"visible"
	"celibate"
	"well-fed"
	"cheery"
	"shiny"
	"confident"
	"democratic"
	"cuddly"
	"furry"
}

bMotion_abstract_register "nice_adverb" {
	"happily"
	"nicely"
	"sexily"
	"cutely"
	"visibly"
	"confidently"
	"lovingly"
}

bMotion_abstract_register "nice_being" {
	"angel"
	"baby"
	"kitten"
	"rainbow"
	"puppy"
	"guinea pig"
	"rabbit"
	"bunny"
	"fish"
	"cat"
	"sheep"
	"fluffy cloud"
}

bMotion_abstract_register "nice_beings" {
	"angels"
	"babies"
	"kittens"
	"rainbows"
	"puppies"
	"guinea pigs"
	"rabbits"
	"bunnies"
	"fish"
	"cats"
	"sheep"
	"fluffy clouds"
}

bMotion_abstract_register "nice_paintstuff" {
	"coffee"
	"tea"
	"hot chocolate"
	"chocolate"
	"chocolate body paint"
	"coffee body paint"
	"custard"
}

bMotion_abstract_register "nice_paintbodypart" {
	"nose"
	"head"
	"paws"
	"fluffy bits"
}

bMotion_abstract_register "nice_paintbodyparts" {
	"noses"
	"heads"
	"paws"
	"fluffy bits"
}

bMotion_abstract_register "nice_beingverb" {
	"pouring %VAR{nice_paintstuff} over"
	"petting"
	"hugging"
	"stroking"
	"admiring"
	"dancing with"
	"squeezing"
}

bMotion_abstract_register "nice_place" {
	"lounge"
	"park"
	"ballpond"
	"bedroom"
	"bouncy castle"
}

bMotion_abstract_register "nice_thing" {
	"foam pointing hand"
	"cup of coffee"
	"cup of tea"
	"cup of hot chocolate"
	"bunch of roses"
	"cotton wool ball"
}

bMotion_abstract_register "nice_things" {
	"foam pointing hands"
	"cups of coffee"
	"cups of tea"
	"cups of hot chocolate"
	"bunches of roses"
	"cotton wool balls"
}

bMotion_abstract_register "nice_thingverb" {
	"hugging"
	"enjoying"
	"drinking"
	"admiring"
	"waving"
}

bMotion_abstract_register "nice_selfverb" {
	"hugging each other"
	"enjoying each other"
	"petting each other"
	"stroking each other"
	"admiring each other"
}

bMotion_abstract_register "inon" {
"in"
"on"
"over"
}

bMotion_abstract_register "coveredin" {
"%VAR{paintstuff} covered"
}

bMotion_abstract_register "nice_coveredin" {
	"%VAR{nice_paintstuff} covered"
}

bMotion_abstract_register "fulladjective" {
"%VAR{adjective}"
"%VAR{adjective}, %VAR{adjective}"
"%VAR{coveredin}"
"%VAR{adjective}, %VAR{coveredin}"
}

bMotion_abstract_register "nice_fulladjective" {
	"%VAR{nice_adjective}"
	"%VAR{nice_adjective}, %VAR{nice_adjective}"
	"%VAR{nice_coveredin}"
	"%VAR{nice_adjective}, %VAR{nice_coveredin}"
}

bMotion_abstract_register "fulladjectives" {
"%VAR{amount} %VAR{adjective}"
"%VAR{amount} %VAR{adjective}, %VAR{adjective}"
"%VAR{amount} %VAR{coveredin}"
"%VAR{amount} %VAR{adjective}, %VAR{coveredin}"
}

bMotion_abstract_register "nice_fulladjectives" {
	"%VAR{amount} %VAR{nice_adjective}"
	"%VAR{amount} %VAR{nice_adjective}, %VAR{nice_adjective}"
	"%VAR{amount} %VAR{nice_coveredin}"
	"%VAR{amount} %VAR{nice_adjective}, %VAR{nice_coveredin}"
}

bMotion_abstract_register "fullbeing" {
"%VAR{being}"
"%VAR{fulladjective} %VAR{being}"
}

bMotion_abstract_register "nice_fullbeing" {
	"%VAR{nice_being}"
	"%VAR{nice_fulladjective} %VAR{nice_being}"
}

bMotion_abstract_register "fullbeings" {
"%VAR{amount} %VAR{beings}"
"%VAR{amount} %VAR{fulladjective} %VAR{beings}"
}

bMotion_abstract_register "nice_fullbeings" {
	"%VAR{amount} %VAR{nice_beings}"
	"%VAR{amount} %VAR{nice_fulladjectives} %VAR{nice_beings}"
}

bMotion_abstract_register "fullbodypart" {
"%VAR{paintbodypart}"
"%VAR{paintbodyparts}"
}

bMotion_abstract_register "nice_fullbodypart" {
	"%VAR{nice_paintbodypart}"
	"%VAR{nice_paintbodyparts}"
}

bMotion_abstract_register "nice_fullthing" {
"%VAR{nice_thing}"
"%VAR{nice_fulladjective} %VAR{nice_thing}"
"%VAR{paintbodypart}"
"%VAR{nice_fulladjective} %VAR{paintbodypart}"
}

bMotion_abstract_register "fullthings" {
"%VAR{amount} %VAR{nice_things}"
"%VAR{nice_fulladjectives} %VAR{nice_things}"
"%VAR{amount} %VAR{paintbodyparts}"
"%VAR{nice_fulladjectives} %VAR{paintbodyparts}"
}

bMotion_abstract_register "nice_fullplace" {
"%VAR{nice_place}"
"%VAR{nice_place} of %VAR{material}"
"%VAR{nice_fulladjective} %VAR{nice_place}"
"%VAR{nice_fulladjective} %VAR{nice_place} of %VAR{material}"
}

bMotion_abstract_register "nicemare" {
	"a %VAR{nice_fullthing} %VAR{nice_thingverb} a %VAR{nice_fullthing}"
	"a %VAR{fullthings} %VAR{nice_thingverb} a %VAR{nice_fullthing}"
	"a %VAR{nice_fullthing} %VAR{nice_thingverb} a %VAR{fullthings}"
	"a %VAR{fullthings} %VAR{nice_thingverb} a %VAR{fullthings}"
	"a %VAR{nice_fullthing} %VAR{nice_thingverb} a %VAR{nice_fullplace}"
	"a %VAR{fullthings} %VAR{nice_thingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullthing} %VAR{nice_thingverb} a %VAR{nice_fullthing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{fullthings} %VAR{nice_thingverb} a %VAR{nice_fullthing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullthing} %VAR{nice_thingverb} a %VAR{fullthings} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{fullthings} %VAR{nice_thingverb} a %VAR{fullthings} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_thingverb} a %VAR{nice_fullthing}"
	"a %VAR{nice_fullbeings} %VAR{nice_thingverb} a %VAR{nice_fullthing}"
	"a %VAR{nice_fullbeing} %VAR{nice_thingverb} a %VAR{fullthings}"
	"a %VAR{nice_fullbeings} %VAR{nice_thingverb} a %VAR{fullthings}"
	"a %VAR{nice_fullbeing} %VAR{nice_thingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_thingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_thingverb} a %VAR{nice_fullthing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_thingverb} a %VAR{nice_fullthing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_thingverb} a %VAR{fullthings} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_thingverb} a %VAR{fullthings} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullthing} %VAR{nice_thingverb} a %VAR{nice_fullbeing}"
	"a %VAR{fullthings} %VAR{nice_thingverb} a %VAR{nice_fullbeing}"
	"a %VAR{nice_fullthing} %VAR{nice_thingverb} a %VAR{nice_fullbeings}"
	"a %VAR{fullthings} %VAR{nice_thingverb} a %VAR{nice_fullbeings}"
	"a %VAR{nice_fullthing} %VAR{nice_thingverb} a %VAR{nice_fullplace}"
	"a %VAR{fullthings} %VAR{nice_thingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullthing} %VAR{nice_thingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{fullthings} %VAR{nice_thingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullthing} %VAR{nice_thingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{fullthings} %VAR{nice_thingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_beingverb} a %VAR{nice_fullbeing}"
	"a %VAR{nice_fullbeings} %VAR{nice_beingverb} a %VAR{nice_fullbeing}"
	"a %VAR{nice_fullbeing} %VAR{nice_beingverb} a %VAR{nice_fullbeings}"
	"a %VAR{nice_fullbeings} %VAR{nice_beingverb} a %VAR{nice_fullbeings}"
	"a %VAR{nice_fullbeing} %VAR{nice_beingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_beingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_beingverb} a %VAR{nice_fullbeing}"
	"a %VAR{nice_fullbeings} %VAR{nice_beingverb} a %VAR{nice_fullbeing}"
	"a %VAR{nice_fullbeing} %VAR{nice_beingverb} a %VAR{nice_fullbeings}"
	"a %VAR{nice_fullbeings} %VAR{nice_beingverb} a %VAR{nice_fullbeings}"
	"a %VAR{nice_fullbeing} %VAR{nice_beingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_beingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullplace}"
	"a %VAR{nice_fullplace}"
	"a %VAR{nice_fullplace}"
	"a %VAR{nice_fullplace}"
	"a %VAR{nice_fullplace}"
	"a %VAR{nice_fullplace}"
	"a %VAR{nice_fullplace}"
	"a %VAR{nice_fullplace}"
	"a %VAR{nice_fullplace}"
	"a %VAR{nice_fullplace}"
	"a %VAR{nice_fullplace}"
	"a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_thingverb} a %VAR{nice_fullthing}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_thingverb} a %VAR{nice_fullthing}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_thingverb} a %VAR{fullthings}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_thingverb} a %VAR{fullthings}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_thingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_thingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_thingverb} a %VAR{nice_fullthing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_thingverb} a %VAR{nice_fullthing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_thingverb} a %VAR{fullthings} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_thingverb} a %VAR{fullthings} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeing}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeing}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeings}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeings}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} and a %VAR{nice_fullbeing} %VAR{nice_selfverb}"
	"a %VAR{nice_fullbeings} and a %VAR{nice_fullbeing} %VAR{nice_selfverb}"
	"a %VAR{nice_fullbeing} and a %VAR{nice_fullbeings} %VAR{nice_selfverb}"
	"a %VAR{nice_fullbeings} and a %VAR{nice_fullbeings} %VAR{nice_selfverb}"
	"a %VAR{nice_fullbeings} %VAR{nice_selfverb}"
	"a %VAR{nice_fullbeing} and a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_selfverb}"
	"a %VAR{nice_fullbeings} and a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_selfverb}"
	"a %VAR{nice_fullbeing} and a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_selfverb}"
	"a %VAR{nice_fullbeings} and a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_selfverb}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_selfverb}"
	"a %VAR{nice_fullbeing} and a %VAR{nice_fullbeing} %VAR{nice_selfverb} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} and a %VAR{nice_fullbeing} %VAR{nice_selfverb} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} and a %VAR{nice_fullbeings} %VAR{nice_selfverb} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} and a %VAR{nice_fullbeings} %VAR{nice_selfverb} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_selfverb} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} and a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_selfverb} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} and a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_selfverb} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} and a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_selfverb} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} and a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_selfverb} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_selfverb} %VAR{inon} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeing} with a %VAR{nice_fullthing}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeing} with a %VAR{fullthings}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeings} with a %VAR{nice_fullthing}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeings} with a %VAR{fullthings}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullplace}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace} with a %VAR{nice_fullthing}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace} with a %VAR{fullthings}"
	"a %VAR{nice_fullbeing} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace} with a %VAR{nice_fullthing}"
	"a %VAR{nice_fullbeings} %VAR{nice_adverb} %VAR{nice_beingverb} a %VAR{nice_fullbeing} %VAR{inon} a %VAR{nice_fullplace} with a %VAR{fullthings}"
}

bMotion_abstract_register "nightmare" {
"a %VAR{fullthing} %VAR{thingverb} a %VAR{fullthing}"
"a %VAR{fullthings} %VAR{thingverb} a %VAR{fullthing}"
"a %VAR{fullthing} %VAR{thingverb} a %VAR{fullthings}"
"a %VAR{fullthings} %VAR{thingverb} a %VAR{fullthings}"
"a %VAR{fullthing} %VAR{thingverb} a %VAR{fullplace}"
"a %VAR{fullthings} %VAR{thingverb} a %VAR{fullplace}"
"a %VAR{fullthing} %VAR{thingverb} a %VAR{fullthing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullthings} %VAR{thingverb} a %VAR{fullthing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullthing} %VAR{thingverb} a %VAR{fullthings} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullthings} %VAR{thingverb} a %VAR{fullthings} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{thingverb} a %VAR{fullthing}"
"a %VAR{fullbeings} %VAR{thingverb} a %VAR{fullthing}"
"a %VAR{fullbeing} %VAR{thingverb} a %VAR{fullthings}"
"a %VAR{fullbeings} %VAR{thingverb} a %VAR{fullthings}"
"a %VAR{fullbeing} %VAR{thingverb} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{thingverb} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{thingverb} a %VAR{fullthing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{thingverb} a %VAR{fullthing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{thingverb} a %VAR{fullthings} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{thingverb} a %VAR{fullthings} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullthing} %VAR{thingverb} a %VAR{fullbeing}"
"a %VAR{fullthings} %VAR{thingverb} a %VAR{fullbeing}"
"a %VAR{fullthing} %VAR{thingverb} a %VAR{fullbeings}"
"a %VAR{fullthings} %VAR{thingverb} a %VAR{fullbeings}"
"a %VAR{fullthing} %VAR{thingverb} a %VAR{fullplace}"
"a %VAR{fullthings} %VAR{thingverb} a %VAR{fullplace}"
"a %VAR{fullthing} %VAR{thingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullthings} %VAR{thingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullthing} %VAR{thingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullthings} %VAR{thingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{beingverb} a %VAR{fullbeing}"
"a %VAR{fullbeings} %VAR{beingverb} a %VAR{fullbeing}"
"a %VAR{fullbeing} %VAR{beingverb} a %VAR{fullbeings}"
"a %VAR{fullbeings} %VAR{beingverb} a %VAR{fullbeings}"
"a %VAR{fullbeing} %VAR{beingverb} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{beingverb} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{beingverb} a %VAR{fullbeing}"
"a %VAR{fullbeings} %VAR{beingverb} a %VAR{fullbeing}"
"a %VAR{fullbeing} %VAR{beingverb} a %VAR{fullbeings}"
"a %VAR{fullbeings} %VAR{beingverb} a %VAR{fullbeings}"
"a %VAR{fullbeing} %VAR{beingverb} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{beingverb} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullplace}"
"a %VAR{fullplace}"
"a %VAR{fullplace}"
"a %VAR{fullplace}"
"a %VAR{fullplace}"
"a %VAR{fullplace}"
"a %VAR{fullplace}"
"a %VAR{fullplace}"
"a %VAR{fullplace}"
"a %VAR{fullplace}"
"a %VAR{fullplace}"
"a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{thingverb} a %VAR{fullthing}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{thingverb} a %VAR{fullthing}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{thingverb} a %VAR{fullthings}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{thingverb} a %VAR{fullthings}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{thingverb} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{thingverb} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{thingverb} a %VAR{fullthing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{thingverb} a %VAR{fullthing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{thingverb} a %VAR{fullthings} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{thingverb} a %VAR{fullthings} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeing}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeing}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeings}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeings}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{beingverb} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{beingverb} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} and a %VAR{fullbeing} %VAR{selfverb}"
"a %VAR{fullbeings} and a %VAR{fullbeing} %VAR{selfverb}"
"a %VAR{fullbeing} and a %VAR{fullbeings} %VAR{selfverb}"
"a %VAR{fullbeings} and a %VAR{fullbeings} %VAR{selfverb}"
"a %VAR{fullbeings} %VAR{selfverb}"
"a %VAR{fullbeing} and a %VAR{fullbeing} %VAR{adverb} %VAR{selfverb}"
"a %VAR{fullbeings} and a %VAR{fullbeing} %VAR{adverb} %VAR{selfverb}"
"a %VAR{fullbeing} and a %VAR{fullbeings} %VAR{adverb} %VAR{selfverb}"
"a %VAR{fullbeings} and a %VAR{fullbeings} %VAR{adverb} %VAR{selfverb}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{selfverb}"
"a %VAR{fullbeing} and a %VAR{fullbeing} %VAR{selfverb} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} and a %VAR{fullbeing} %VAR{selfverb} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} and a %VAR{fullbeings} %VAR{selfverb} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} and a %VAR{fullbeings} %VAR{selfverb} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{selfverb} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} and a %VAR{fullbeing} %VAR{adverb} %VAR{selfverb} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} and a %VAR{fullbeing} %VAR{adverb} %VAR{selfverb} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} and a %VAR{fullbeings} %VAR{adverb} %VAR{selfverb} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} and a %VAR{fullbeings} %VAR{adverb} %VAR{selfverb} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{selfverb} %VAR{inon} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeing} with a %VAR{fullthing}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeing} with a %VAR{fullthings}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeings} with a %VAR{fullthing}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeings} with a %VAR{fullthings}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{beingverb} a %VAR{fullplace}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{beingverb} a %VAR{fullplace}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace} with a %VAR{fullthing}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace} with a %VAR{fullthings}"
"a %VAR{fullbeing} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace} with a %VAR{fullthing}"
"a %VAR{fullbeings} %VAR{adverb} %VAR{beingverb} a %VAR{fullbeing} %VAR{inon} a %VAR{fullplace} with a %VAR{fullthings}"
}

# Add ourselves to places
bMotion_abstract_add "randomStuff" "A%REPEAT{4:8:R}GH%REPEAT{1:5:!} I had a horrible nightmare of %VAR{nightmare} %VAR{unsmiles}"
bMotion_abstract_add "goodnights" "Don't have a nightmare about %VAR{nightmare}!"

# We don't add plugins, so don't complain
set bMotion_noplugins 1

